name: powerlesstaxpayer
favicon: null
layout_spectrum: 0.1115599365439266
typography_spectrum: 0.5980266451369971
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c0c0c0'
    - '#1d100a'
    - '#878785'
    - '#666867'
    - '#4b4a48'
  brandStrength: 0.37566510704346
  lightness: 0.2445183559320867
  saturation: 0.5616146735846996
  rhythmicContrast: 0.7104224688373506
purpose: []
